/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafx-plugin") version "0.1.0"
}

javafx {
    version = "22-ea+11"
    modules = listOf("javafx.controls", "javafx.fxml")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":game_logic"))
    implementation("org.junit.jupiter:junit-jupiter-api:5.12.1")
    runtimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("com.google.guava:guava:32.1.2-jre")
}

tasks.test {
  useJUnitPlatform()
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

repositories {
    mavenCentral()
}
